/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "MainWindow.h"
#include "MainController.h"
#include "MainEditor.h"


//==============================================================================
MainAppWindow::MainAppWindow()
    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                      Colours::lightgrey,
                      DocumentWindow::allButtons)
{
	mMainController = new MainController();
	MainEditor* const contentComponent = new MainEditor(mMainController);
	mMainController->setEditor((MainEditor*)contentComponent);
	setContentComponent (contentComponent, true, true);
    centreWithSize (1024, 768); //+ getTitleBarHeight());
    setUsingNativeTitleBar(true);
	setVisible (true);
	
	
}

MainAppWindow::~MainAppWindow()
{
	delete mMainController;
}

void MainAppWindow::closeButtonPressed()
{
    JUCEApplication::getInstance()->systemRequestedQuit();
}
